# Generated by Django 4.2.29 on 2026-03-05 05:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100, unique=True, verbose_name='رقم العقد')),
                ('start_date', models.DateField(verbose_name='تاريخ بداية العقد')),
                ('end_date', models.DateField(verbose_name='تاريخ نهاية العقد')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قيمة الإيجار (بدون ضريبة)')),
                ('has_tax', models.BooleanField(default=True, verbose_name='تطبق الضريبة؟')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الضريبة (%)')),
                ('payment_interval', models.CharField(choices=[('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('yearly', 'سنوي')], default='monthly', max_length=20, verbose_name='دورة السداد')),
                ('is_active', models.BooleanField(default=True, verbose_name='العقد ساري؟')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'عقد',
                'verbose_name_plural': 'العقود',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الفئة الرئيسية')),
                ('description', models.TextField(blank=True, verbose_name='وصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'فئة رئيسية',
                'verbose_name_plural': 'الفئات الرئيسية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم القسم الداخلي')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='الموقع')),
                ('description', models.TextField(blank=True, verbose_name='وصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='rentals.maincategory', verbose_name='الفئة الرئيسية')),
            ],
            options={
                'verbose_name': 'قسم داخلي',
                'verbose_name_plural': 'الأقسام الداخلية',
                'ordering': ['main_category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('identity_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الهوية/الإقامة')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الجوال')),
                ('phone2', models.CharField(blank=True, max_length=20, verbose_name='جوال آخر')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
            ],
            options={
                'verbose_name': 'مستأجر',
                'verbose_name_plural': 'المستأجرون',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=50, verbose_name='رقم/اسم الوحدة')),
                ('unit_type', models.CharField(choices=[('shop', 'محل تجاري'), ('apartment', 'شقة سكنية'), ('room', 'غرفة'), ('farm_unit', 'وحدة زراعية (حقل/بيت محمي)'), ('office', 'مكتب'), ('warehouse', 'مستودع'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الوحدة')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='الدور')),
                ('area', models.FloatField(blank=True, null=True, verbose_name='المساحة (م²)')),
                ('is_rented', models.BooleanField(default=False, verbose_name='مؤجرة حالياً؟')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='rentals.subcategory', verbose_name='القسم الداخلي')),
            ],
            options={
                'verbose_name': 'وحدة',
                'verbose_name_plural': 'الوحدات',
                'ordering': ['sub_category', 'unit_number'],
                'unique_together': {('sub_category', 'unit_number')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='تاريخ الدفع')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المدفوع')),
                ('for_period_start', models.DateField(verbose_name='بداية الفترة المدفوعة')),
                ('for_period_end', models.DateField(verbose_name='نهاية الفترة المدفوعة')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('bank', 'تحويل بنكي'), ('check', 'شيك')], default='cash', max_length=30, verbose_name='طريقة الدفع')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='رقم المرجع/الشيك')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rentals.contract', verbose_name='العقد')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='rentals.tenant', verbose_name='المستأجر'),
        ),
        migrations.AddField(
            model_name='contract',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='rentals.unit', verbose_name='الوحدة'),
        ),
    ]
