# Generated by Django 4.2.29 on 2026-03-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='end_date',
        ),
        migrations.AddField(
            model_name='contract',
            name='lease_duration_months',
            field=models.PositiveIntegerField(default=12, verbose_name='مدة العقد (بالأشهر)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='rent_type',
            field=models.CharField(choices=[('monthly', 'شهري'), ('yearly', 'سنوي')], default='monthly', max_length=10, verbose_name='نوع الإيجار'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_interval',
            field=models.CharField(choices=[('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('half_yearly', 'نصف سنوي'), ('yearly', 'سنوي')], default='monthly', max_length=20, verbose_name='دورة السداد'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قيمة الإيجار'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
