# Generated by Django 4.2.29 on 2026-03-05 07:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_remove_contract_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('shop', 'محل تجاري'), ('apartment', 'شقة سكنية'), ('room', 'غرفة'), ('farm_unit', 'وحدة زراعية'), ('office', 'مكتب'), ('warehouse', 'مستودع'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الوحدة'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ المصروف')),
                ('description', models.CharField(max_length=255, verbose_name='البيان')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ (شامل الضريبة إن وجدت)')),
                ('has_tax', models.BooleanField(default=False, verbose_name='المبلغ شامل الضريبة؟')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الضريبة (%)')),
                ('tax_refundable', models.BooleanField(default=False, verbose_name='الضريبة قابلة للاسترداد؟')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='rentals.subcategory', verbose_name='القسم الداخلي')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصروفات',
                'ordering': ['-date'],
            },
        ),
    ]
