# Generated by Django 4.2.29 on 2026-03-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_alter_unit_unit_type_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='expenses/%Y/%m/', verbose_name='مرفق (فاتورة)'),
        ),
    ]
