# Generated by Django 4.2.29 on 2026-03-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_expense_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='محذوف؟'),
        ),
    ]
