# Generated by Django 4.2.29 on 2026-03-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_tenant_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='id_image',
            field=models.ImageField(blank=True, null=True, upload_to='tenants/%Y/%m/', verbose_name='صورة الهوية'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='identity_number',
            field=models.CharField(max_length=50, verbose_name='رقم الهوية/الإقامة'),
        ),
        migrations.AlterUniqueTogether(
            name='tenant',
            unique_together={('identity_number', 'is_deleted')},
        ),
    ]
