# Generated by Django 4.2.29 on 2026-03-06 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_tenant_id_image_alter_tenant_identity_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='tenant',
            unique_together=set(),
        ),
    ]
