# Generated by Django 4.2.29 on 2026-03-06 04:53

from django.db import migrations, models
import rentals.models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_alter_tenant_options_alter_tenant_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['name'], 'verbose_name': 'مستأجر', 'verbose_name_plural': 'المستأجرون'},
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/', verbose_name='ملف العقد'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='payments/%Y/%m/', verbose_name='صورة الإيصال'),
        ),
        migrations.AddField(
            model_name='unit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='units/%Y/%m/', verbose_name='صورة الوحدة'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='id_image',
            field=models.ImageField(blank=True, null=True, upload_to=rentals.models.tenant_id_path, verbose_name='صورة الهوية'),
        ),
        migrations.AlterUniqueTogether(
            name='tenant',
            unique_together={('identity_number', 'is_deleted')},
        ),
    ]
