# Generated by Django 4.2.29 on 2026-03-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_alter_tenant_options_contract_contract_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='grace_period_days',
            field=models.PositiveIntegerField(default=0, help_text='عدد الأيام قبل بداية العقد التي لا تحتسب فيها الضريبة', verbose_name='فترة السماح (أيام)'),
        ),
    ]
