# Generated by Django 4.2.29 on 2026-03-11 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_contract_grace_period_days'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tenant',
            unique_together=set(),
        ),
    ]
